name: wind-spores
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.8
    - flake8=3.8.3
    - snakemake-minimal=6.1.1
    - pandas=1.2.0
    - xarray=0.19.0
    - netcdf4=1.5.6
