__default__:
    runtime: 100
    cores: 1
    memory: 50000
    output: "build/logs/{rule}.{wildcards}.log"
    name: "{rule}.{wildcards}"
turbine_metrics_per_gridcell:
    memory: 100000
    runtime: 240
