__default__:
    runtime: 100
    cores: 1
    memory: 50000
    output: "build/logs/{rule}.{wildcards}.log"
    name: "{rule}.{wildcards}"
turbine_metrics_per_gridcell:
    memory: 100000
    runtime: 240
turbine_output_single_all_heights:
    memory: 100000
cluster_model_regions:
    cores: 5
    memory: 10000
    runtime: 240
test_clusters:
    cores: 5
    memory: 20000
    runtime: 100
