data-sources:
    cosmo-rea2-wind-speed-coeffs: "data/cosmo_rea2_A_Z/{year}.nc"
    cosmo-rea2-coords: "data/cosmo_rea2_coords.nc"
    height-weights:  # importance of different wind heights in fitting a log-law curve. Bigger number = better matching fit to that wind height
        50: 2
        75: 3
        100: 4
        150: 3
        200: 2
    x-name: "west_east"
    y-name: "south_north"
    lat-name: XLAT
    lon-name: XLON
    first-year: 2009
    final-year: 2018
    long-name: NEWA

cosmo-rea2:
    pole-latitude: 40
    pole-longitude: -170
    x-name: "rlon"
    y-name: "rlat"
    lat-name: RLAT
    lon-name: RLON
    first-year: 2007
    final-year: 2013
    long-name: COSMO-REA2

ch-bounding-box:
    lat-range: [45.47, 48.14]
    lon-range: [5.49, 10.80]

cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/wind-spores/
    local-results-dir: build/cluster
