name: default
channels:
    - conda-forge
dependencies:
    - python=3.8
    - numpy=1.22.2
    - pandas=1.4.0
    - xarray=0.21.1
    - scikit-learn=1.0.2
    - netcdf4=1.5.8
    - ipython=8.0.1
    - ipdb=0.13.9
